// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AWS: typeof import('./src/components/Icons/Backend/AWS.vue')['default']
    Cplus: typeof import('./src/components/Icons/Other/Cplus.vue')['default']
    CSharp: typeof import('./src/components/Icons/Other/CSharp.vue')['default']
    CSS: typeof import('./src/components/Icons/frontend/CSS.vue')['default']
    FireBase: typeof import('./src/components/Icons/Backend/FireBase.vue')['default']
    GitHub: typeof import('./src/components/Icons/gitHub.vue')['default']
    Go: typeof import('./src/components/Icons/Other/Go.vue')['default']
    HomePage: typeof import('./src/components/templates/Pages/HomePage.vue')['default']
    HTML: typeof import('./src/components/Icons/frontend/HTML.vue')['default']
    JavaScript: typeof import('./src/components/Icons/frontend/JavaScript.vue')['default']
    Linkedin: typeof import('./src/components/Icons/Linkedin.vue')['default']
    Logo: typeof import('./src/components/Icons/Logo.vue')['default']
    Mongo: typeof import('./src/components/Icons/Backend/Mongo.vue')['default']
    MySQL: typeof import('./src/components/Icons/Backend/MySQL.vue')['default']
    NavBar: typeof import('./src/components/templates/NavBar.vue')['default']
    Node: typeof import('./src/components/Icons/Backend/Node.vue')['default']
    ProjectPage: typeof import('./src/components/templates/Pages/ProjectPage.vue')['default']
    Python: typeof import('./src/components/Icons/Other/Python.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Serverless: typeof import('./src/components/Icons/Backend/Serverless.vue')['default']
    Tailwind: typeof import('./src/components/Icons/frontend/Tailwind.vue')['default']
    Twiter: typeof import('./src/components/Icons/Twiter.vue')['default']
    TypeScript: typeof import('./src/components/Icons/frontend/TypeScript.vue')['default']
    Vue: typeof import('./src/components/Icons/frontend/Vue.vue')['default']
  }
}
