service: Script
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: src/handlers.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /email
          method: post
          cors: true

plugins:
  - serverless-plugin-typescript