export const LinksProjects: any[] = [
    {
        id: 1,
        name: 'Wedding Organization',
        supDescription: 'The graduation project is an wedding system',
        githubLink: 'https://github.com/mohamed-elrefai/Wedding_Orgnization',
        Description: 'The graduation project is an wedding system, goods Inventory',
        linkSite: 'https://nicotinekw.com/',
    },
    {
        id: 2,
        name: 'Auction',
        supDescription: 'Auction is an sell system, goods Inventory, it between member and seller. Admin ',
        githubLink: 'https://github.com/mohamed-elrefai/Wedding_Orgnization',
        Description: 'The auction system provides many features such as adding products and offering them for bidding. Products can be purchased by bidding and winning the auction and the e- wallet contains all transactions',
        linkSite: 'https://nicotinekw.com/',
    },
    {
        id: 3,
        name: 'Ecommerce',
        supDescription: 'Auction is an sell system, goods Inventory, it between member and seller. Admin ',
        githubLink: 'https://github.com/mohamed-elrefai/Wedding_Orgnization',
        Description: '',
        linkSite: 'https://nicotinekw.com/',
    },
    {
        id: 4,
        name: 'Online Grocery Store',
        supDescription: 'The graduation project is an wedding system',
        githubLink: 'https://github.com/mohamed-elrefai/Wedding_Orgnization',
        Description: 'The graduation project is an wedding system, goods Inventory',
        linkSite: 'https://nicotinekw.com/',
    },
    {
        id: 5,
        name: 'Piralfa',
        supDescription: 'Auction is an sell system, goods Inventory, it between member and seller. Admin ',
        githubLink: 'https://github.com/mohamed-elrefai/Wedding_Orgnization',
        Description: 'The auction system provides many features such as adding products and offering them for bidding. Products can be purchased by bidding and winning the auction and the e- wallet contains all transactions',
        linkSite: 'https://nicotinekw.com/',
    },
    {
        id: 6,
        name: 'WALL·E',
        supDescription: 'Auction is an sell system, goods Inventory, it between member and seller. Admin ',
        githubLink: 'https://github.com/mohamed-elrefai/Wedding_Orgnization',
        Description: '',
        linkSite: 'https://nicotinekw.com/',
    },
    {
        id: 7,
        name: 'Gad Restaurant',
        supDescription: 'The graduation project is an wedding system',
        githubLink: 'https://github.com/mohamed-elrefai/Wedding_Orgnization',
        linkSite: 'https://nicotinekw.com/',
        Description: 'The graduation project is an wedding system, goods Inventory',
    },
    {
        id: 8,
        name: 'Nicotine KW',
        supDescription: 'Auction is an sell system, goods Inventory, it between member and seller. Admin ',
        githubLink: 'https://github.com/mohamed-elrefai/Wedding_Orgnization',
        linkSite: 'https://nicotinekw.com/',
        Description: 'The auction system provides many features such as adding products and offering them for bidding. Products can be purchased by bidding and winning the auction and the e- wallet contains all transactions',
    },
    {
        id: 9,
        name: 'Salt and stone boston',
        supDescription: 'Salt + Stone is the first independent restaurant from restaurateurs Sean and Sue Olson',
        githubLink: '',
        linkSite: 'https://saltandstoneboston.com/',
        Description: 'Salt + Stone is the first independent restaurant from restaurateurs Sean and Sue Olson. The couple has over 40 years in the restaurant and hospitality industry working with major restaurants brands, independent catering companies, and fresh seafood and meat markets. Based on years of traveling, knowledge of sourcing, and family recipes, Salt + Stone brings the best ingredients and preparation to the plate in a casual, modern atmosphere.Located in the heart of Assembly Row(Somerville, MA) minutes from downtown Boston, the restaurant boasts a vibrant atmosphere with floor to ceiling windows, two extensive bars, a raw bar, private small dining area, and outdoor covered patio pavilion with full - service.Come enjoy our creative cocktails, and amazing appetizers, steaks, seafood, flatbread, salads, sandwiches, pastas and more!',
    },
    {
        id: 10,
        name: 'Egypt tours planner',
        supDescription: 'Offers a variety of Egypt tour packages that are customized not only to your personality but to your budget.',
        githubLink: '',
        linkSite: 'https://egypttoursplanner.com/',
        Description: 'Is experienced planning tours in Egypt. we know that planning the trip of a lifetime is exciting. That is why we help you build those memories with luxury and adventure tours, romantic honeymoon packages, safaris and cruises. Let Egypt Tours Planner help you Fulfill your travel dreams with your next trip. EGYPT TOURS PLANNER, offers a variety of Egypt tour packages that are customized not only to your personality but to your budget.You will be surprised at what your budget can afford.Everyone should experience the beauty of Egypt.We can plan a getaway that would make any foodie fall in love, a risk- taker blush, and romantics escape.Egypt has something for everyone, our vibrant Bazaar in Egypt, scrumptious cuisine, sacred mosques, and hidden pyramids are just the start! Our tours can be planned anywhere in Egypt.',
    }

]